[package]
name = "spritezip"
version = "0.1.0"
authors = ["Daniel Wong <drojfjord@gmail.com>"]

[dependencies]
image = "*"
brotli = "2.5.0"
time = "*"
walkdir = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bincode = "1.0"
number_prefix = "*"